var appApplyLoan = require('../controllers/appApplyLoanController');  

module.exports = function (app) {
  app.get('/api/apply_loan/all', appApplyLoan.getAllApplyLoan);
  app.get('/api/apply_loan/get_all/first_reviewer_loan/:limit/:offset', appApplyLoan.getFirstReviewerLoan); 
  app.get('/api/apply_loan/get_all/second_reviewer_loan/:limit/:offset', appApplyLoan.getSecondReviewerLoan);  
  app.get('/api/apply_loan/all_with_user', appApplyLoan.getAllLoanWithUser);
  app.get('/api/apply_loan/search_all_with_user', appApplyLoan.getSearchAllLoanWithUser);
  app.get('/api/apply_loan/status', appApplyLoan.getLoanStatus);
  app.get('/api/apply_loan/by_id', appApplyLoan.getApplyLoanById);
  app.get('/api/apply_loan/:loan_id/:id', appApplyLoan.getApplyLoanByLoanId);
  app.get('/api/re_payment_history/:loan_id', appApplyLoan.getPaymentHistoryByLoanId);
  app.get('/api/apply_loan/customer/loan_history/:customer_id', appApplyLoan.getApplyLoanByCustomerId);
  app.get('/api/apply_loan/approved/all/by_id', appApplyLoan.getAllApproveApplyLoanById); 
  app.get('/api/apply_loan/process/user/by_id', appApplyLoan.getAllProcessApplyLoanById); 
  app.get('/api/apply_loan/paid/user/by_id', appApplyLoan.getAllPaidApplyLoanById);
  app.post('/api/apply_loan/save_apply_loan', appApplyLoan.saveApplyLoan);
  app.post('/api/apply_loan/status', appApplyLoan.changeLoanStatus);
  app.post('/api/apply_loan/disbursal_status', appApplyLoan.changeLoanStatusDisbursal);
  app.post('/api/apply_loan/pending_status', appApplyLoan.changeLoanStatusPending);
  app.post('/api/apply_loan/banned_status', appApplyLoan.changeLoanStatusBanned);
  app.post('/api/apply_loan/unbanned_status', appApplyLoan.changeLoanStatusUnBanned);
  app.get('/api/apply_loan/pay', appApplyLoan.getAllApplyloanWithPayment);
  app.get('/api/apply_loan/flat', appApplyLoan.getAllApplyloanWithFlat);
  app.get('/api/apply_loan/business_flat', appApplyLoan.getAllApplyloanWithBusinessFlat);
  app.get('/api/apply_loan/search_business_flat', appApplyLoan.getSearchAllApplyBusinessloanWithFlat);
  app.get('/api/apply_loan/search_flat', appApplyLoan.getSearchAllApplyloanWithFlat);
  app.get('/api/apply_loan/overall_collection/:offset/:limit', appApplyLoan.getOverallCollectionApplyloan); 
  app.get('/api/apply_loan/overall_business_collection/:offset/:limit', appApplyLoan.getOverallBusinessCollectionLoan);  
  app.post('/api/apply_loan/send_mail', appApplyLoan.sendLoanMail);
  app.post('/api/apply_loan/loan_agreement_by_loan_id', appApplyLoan.getLoanAgreementByLoanId);
  app.post('/api/apply_loan/get_transactions_by_loan_id',appApplyLoan.getTransactionsAdmin);
  app.post('/apis/get_transactions/by_loan_id',appApplyLoan.getTransactions);
  app.get('/api/apply_loan/all_case_review_loan/:offset/:limit', appApplyLoan.getAllCaseReviewLoan); 
  app.post('/api/apply_loan/approved/send_mail', appApplyLoan.sendApprovedLoanMail);
  app.get('/api/apply_loan/latest/apply/loan', appApplyLoan.getLatestLoanData);
  app.post('/api/apply_loan/remark/submit_remark', appApplyLoan.submitRemark);
  app.get('/api/apply_loan/remark/get_reviewer_remark/:loan_id', appApplyLoan.getReviewerLoanRemarks);
  app.get('/api/apply_loan/remark/get_collection_remark/:loan_id', appApplyLoan.getCollectionLoanRemarks);
  app.get('/api/apply_loan/customer_details/get_all_loan/:offset/:limit', appApplyLoan.getAllLoanOfCustomerDetails);
  app.get('/api/apply_loan/overall/get_loans/:offset/:limit', appApplyLoan.getOverAllApplyLoan);
  app.get('/api/apply_loan/approval_report/get_loans/:offset/:limit', appApplyLoan.getApprovalReportApplyLoan);
  app.get('/apis/apply_loan/edit_loan/get_search_loans/:loan_id', appApplyLoan.getLoanForEditSearch);
  app.get('/apis/apply_loan/edit_loan/get_edit_loan/:loan_id/:user_id', appApplyLoan.getLoanForEdit);
  app.post('/apis/apply_loan/edit_loan/save_editloan', appApplyLoan.saveEditLoan);
  app.post('/apis/apply_loan/get_transactions/by_loan_id',appApplyLoan.getEmployeeTransactions);
};