var systemReport = require('../controllers/systemReportController');  

module.exports = function (app) {
  app.get('/api/system_report/collection/get_reviewers', systemReport.getReviewerLoans);
  app.post('/api/system_report/collection/get_reviewers_report/:offset/:limit', systemReport.getReviewerLoansReport); 
  app.get('/api/system_report/collection/get_collections', systemReport.getCollectionLoans);
  app.get('/api/system_report/collection/get_collections_report/:offset/:limit', systemReport.getCollectionLoansReport);
  app.get('/api/system_report/get/collection_teams', systemReport.getCollectionTeams);
  app.get('/api/system_report/get/business_collection_teams', systemReport.getBusinessCollectionTeams);
  app.get('/api/system_report/get/business_assigner_list', systemReport.getBusinessAssignerList);
  app.get('/api/system_report/get/assigner_list', systemReport.getAssignerList); 
  app.get('/api/system_report/get/reviewers', systemReport.getReviewers);
  app.get('/api/system_report/get/reviewer_assigner', systemReport.getReviewerAssigner);
  app.get('/api/system_report/get/search_overall_collection', systemReport.getSearchOverallCollection); 
  app.get('/api/system_report/get/search_overall_business_collection', systemReport.getSearchOverallBusinessCollection);
  app.get('/api/system_report/reviewer/get_status/:reviewer_id', systemReport.getAllStatusByReviewer);
  app.get('/api/system_report/reviewer/get_reports', systemReport.getReviewerReports);
  app.get('/api/system_report/collection/get_users/:collection_id', systemReport.getAllUserByCollectionId); 
  app.get('/api/system_report/collection/get_reports', systemReport.getCollectionReports); 
  app.get('/api/system_report/customer_details/search_loan_by_date', systemReport.getSearchCustomerDetailsLoan);
  app.get('/api/system_report/case_review/search_loan_by_date', systemReport.getSearchCaseReviewLoan); 
  app.get('/api/system_report/overall_customer_details/search_loan', systemReport.getSearchOverAllCustomerLoan);
  app.get('/api/system_report/approval_report/search_loan', systemReport.getSearchApprovalReportLoan); 
  app.post('/api/system_report/first_reviewer/search_first_reviewer_loans/:limit/:offset', systemReport.searchFirstReviewerLoans);
  app.post('/api/system_report/second_reviewer/search_second_reviewer_loans/:limit/:offset', systemReport.searchSecondReviewerLoans);
  app.get('/apis/system_report/achivement/get_achivement', systemReport.getAchivement);
  app.get('/apis/system_report/achivement/get_search_achivement', systemReport.getSearchAchivement);
  // app.get('/api/system_report/backup/get_db_backup', systemReport.getExportDB);
  app.get('/apis/system_report/achivement/get_approver_achivement', systemReport.getApproverAchivement);
  app.get('/apis/system_report/achivement/get_search_approver_achivement', systemReport.getSearchApproverAchivement);
  app.post('/api/system_report/add_reminder', systemReport.addReminder);
  app.get('/api/system_report/get_reminder', systemReport.getReminder);
  app.put('/api/system_report/done_reminder', systemReport.doneReminder);
  app.get('/api/system_report/all_tenures', systemReport.getTenures);
  app.get('/apis/system_report/achivement/get_search_approver_achivement', systemReport.getSearchApproverAchivement); 
  app.post('/api/system_report/individual_achievements', systemReport.individualAchievements);
  app.post('/api/system_report/add_extension_deal', systemReport.saveExtensionDeal);
  app.get('/api/system_report/all_extension_deal', systemReport.allExtensionDeal);
   app.get('/api/system_report/get_extend_amount_by_tenure', systemReport.getAmountByTenure);
  app.delete('/api/system_report/delete_extension_deal', systemReport.deleteExtensionDeal);
  app.put('/api/system_report/update_status_extension_deal', systemReport.updateStatusExtensionDeal);
  app.post('/apis/system_report/extension_deals', systemReport.getDeals);
};